---
deployment:
  tasks:
    - export REPOPATH=/home/wvkptxmx/repositories/potnplant-webapp2
    - export DEPLOYPATH=/home/wvkptxmx/public_html
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R $REPOPATH/dist/. $DEPLOYPATH/